// // vocabulary.js
// // This file exports an array of 300 vocabulary objects for HSK 1 and HSK 2.
// // Each object has the following properties:
// //   - level: "HSK1" or "HSK2"
// //   - word: Chinese characters (Simplified)
// //   - pinyin: The pinyin (to be styled larger via CSS)
// //   - meaning: The English definition

export const hskVocabulary = [
  // ================================
  // HSK 1 Vocabulary (150 words)
  // ================================
  { level: "HSK1", word: "我", pinyin: "wǒ", meaning: "I; me" },
  { level: "HSK1", word: "我们", pinyin: "wǒmen", meaning: "we; us" },
  { level: "HSK1", word: "你", pinyin: "nǐ", meaning: "you (singular)" },
  { level: "HSK1", word: "他", pinyin: "tā", meaning: "he; him" },
  { level: "HSK1", word: "她", pinyin: "tā", meaning: "she; her" },
  { level: "HSK1", word: "这", pinyin: "zhè", meaning: "this" },
  { level: "HSK1", word: "那", pinyin: "nà", meaning: "that" },
  { level: "HSK1", word: "哪", pinyin: "nǎ", meaning: "which?" },
  { level: "HSK1", word: "哪儿", pinyin: "nǎr", meaning: "where?" },
  { level: "HSK1", word: "谁", pinyin: "shéi", meaning: "who?" },
  { level: "HSK1", word: "什么", pinyin: "shénme", meaning: "what?" },
  {
    level: "HSK1",
    word: "多少",
    pinyin: "duōshǎo",
    meaning: "how many; how much?",
  },
  { level: "HSK1", word: "几", pinyin: "jǐ", meaning: "a few; how many?" },
  { level: "HSK1", word: "怎么", pinyin: "zěnme", meaning: "how?" },
  { level: "HSK1", word: "怎么样", pinyin: "zěnmeyàng", meaning: "how about?" },
  { level: "HSK1", word: "一", pinyin: "yī", meaning: "one" },
  { level: "HSK1", word: "二", pinyin: "èr", meaning: "two" },
  { level: "HSK1", word: "三", pinyin: "sān", meaning: "three" },
  { level: "HSK1", word: "四", pinyin: "sì", meaning: "four" },
  { level: "HSK1", word: "五", pinyin: "wǔ", meaning: "five" },
  { level: "HSK1", word: "六", pinyin: "liù", meaning: "six" },
  { level: "HSK1", word: "七", pinyin: "qī", meaning: "seven" },
  { level: "HSK1", word: "八", pinyin: "bā", meaning: "eight" },
  { level: "HSK1", word: "九", pinyin: "jiǔ", meaning: "nine" },
  { level: "HSK1", word: "十", pinyin: "shí", meaning: "ten" },
  { level: "HSK1", word: "个", pinyin: "gè", meaning: "(general classifier)" },
  { level: "HSK1", word: "岁", pinyin: "suì", meaning: "(classifier for age)" },
  {
    level: "HSK1",
    word: "本",
    pinyin: "běn",
    meaning: "(classifier for books)",
  },
  { level: "HSK1", word: "些", pinyin: "xiē", meaning: "some; a few" },
  { level: "HSK1", word: "块", pinyin: "kuài", meaning: "piece; chunk" },
  { level: "HSK1", word: "不", pinyin: "bù", meaning: "not; no" },
  { level: "HSK1", word: "没", pinyin: "méi", meaning: "not have; none" },
  { level: "HSK1", word: "很", pinyin: "hěn", meaning: "very" },
  { level: "HSK1", word: "太", pinyin: "tài", meaning: "too; excessively" },
  { level: "HSK1", word: "都", pinyin: "dōu", meaning: "all; both" },
  { level: "HSK1", word: "一点儿", pinyin: "yīdiǎnr", meaning: "a little bit" },
  { level: "HSK1", word: "和", pinyin: "hé", meaning: "and" },
  { level: "HSK1", word: "在", pinyin: "zài", meaning: "in; at" },
  {
    level: "HSK1",
    word: "的",
    pinyin: "de",
    meaning: "(possessive/attributive particle)",
  },
  {
    level: "HSK1",
    word: "了",
    pinyin: "le",
    meaning: "(completed action marker)",
  },
  { level: "HSK1", word: "吗", pinyin: "ma", meaning: "(question particle)" },
  { level: "HSK1", word: "呢", pinyin: "ne", meaning: "(question particle)" },
  { level: "HSK1", word: "喂", pinyin: "wèi", meaning: "hello (on the phone)" },
  { level: "HSK1", word: "家", pinyin: "jiā", meaning: "home; family" },
  { level: "HSK1", word: "学校", pinyin: "xuéxiào", meaning: "school" },
  {
    level: "HSK1",
    word: "饭店",
    pinyin: "fàndiàn",
    meaning: "restaurant; hotel",
  },
  { level: "HSK1", word: "商店", pinyin: "shāngdiàn", meaning: "store; shop" },
  { level: "HSK1", word: "医院", pinyin: "yīyuàn", meaning: "hospital" },
  {
    level: "HSK1",
    word: "火车站",
    pinyin: "huǒchēzhàn",
    meaning: "train station",
  },
  { level: "HSK1", word: "中国", pinyin: "Zhōngguó", meaning: "China" },
  { level: "HSK1", word: "北京", pinyin: "Běijīng", meaning: "Beijing" },
  { level: "HSK1", word: "上", pinyin: "shàng", meaning: "up; on" },
  { level: "HSK1", word: "下", pinyin: "xià", meaning: "down; below" },
  { level: "HSK1", word: "前面", pinyin: "qiánmiàn", meaning: "front" },
  { level: "HSK1", word: "后面", pinyin: "hòumiàn", meaning: "back; behind" },
  { level: "HSK1", word: "里", pinyin: "lǐ", meaning: "inside" },
  { level: "HSK1", word: "今天", pinyin: "jīntiān", meaning: "today" },
  { level: "HSK1", word: "明天", pinyin: "míngtiān", meaning: "tomorrow" },
  { level: "HSK1", word: "昨天", pinyin: "zuótiān", meaning: "yesterday" },
  { level: "HSK1", word: "上午", pinyin: "shàngwǔ", meaning: "morning" },
  { level: "HSK1", word: "中午", pinyin: "zhōngwǔ", meaning: "noon" },
  { level: "HSK1", word: "下午", pinyin: "xiàwǔ", meaning: "afternoon" },
  { level: "HSK1", word: "年", pinyin: "nián", meaning: "year" },
  { level: "HSK1", word: "月", pinyin: "yuè", meaning: "month" },
  { level: "HSK1", word: "号", pinyin: "hào", meaning: "number; date" },
  { level: "HSK1", word: "星期", pinyin: "xīngqī", meaning: "week" },
  { level: "HSK1", word: "点", pinyin: "diǎn", meaning: "o’clock; dot" },
  { level: "HSK1", word: "分钟", pinyin: "fēnzhōng", meaning: "minute" },
  { level: "HSK1", word: "现在", pinyin: "xiànzài", meaning: "now" },
  { level: "HSK1", word: "时候", pinyin: "shíhou", meaning: "time; moment" },
  { level: "HSK1", word: "爸爸", pinyin: "bàba", meaning: "father (informal)" },
  { level: "HSK1", word: "妈妈", pinyin: "māma", meaning: "mother (informal)" },
  { level: "HSK1", word: "儿子", pinyin: "érzi", meaning: "son" },
  { level: "HSK1", word: "女儿", pinyin: "nǚér", meaning: "daughter" },
  { level: "HSK1", word: "老师", pinyin: "lǎoshī", meaning: "teacher" },
  { level: "HSK1", word: "学生", pinyin: "xuéshēng", meaning: "student" },
  { level: "HSK1", word: "同学", pinyin: "tóngxué", meaning: "classmate" },
  { level: "HSK1", word: "朋友", pinyin: "péngyǒu", meaning: "friend" },
  { level: "HSK1", word: "医生", pinyin: "yīshēng", meaning: "doctor" },
  { level: "HSK1", word: "先生", pinyin: "xiānsheng", meaning: "sir; Mr." },
  { level: "HSK1", word: "小姐", pinyin: "xiǎojiě", meaning: "Miss" },
  { level: "HSK1", word: "衣服", pinyin: "yīfu", meaning: "clothes" },
  { level: "HSK1", word: "水", pinyin: "shuǐ", meaning: "water" },
  { level: "HSK1", word: "菜", pinyin: "cài", meaning: "dish; vegetables" },
  { level: "HSK1", word: "米饭", pinyin: "mǐfàn", meaning: "cooked rice" },
  { level: "HSK1", word: "水果", pinyin: "shuǐguǒ", meaning: "fruit" },
  { level: "HSK1", word: "苹果", pinyin: "píngguǒ", meaning: "apple" },
  { level: "HSK1", word: "茶", pinyin: "chá", meaning: "tea" },
  { level: "HSK1", word: "杯子", pinyin: "bēizi", meaning: "cup; glass" },
  { level: "HSK1", word: "钱", pinyin: "qián", meaning: "money" },
  { level: "HSK1", word: "飞机", pinyin: "fēijī", meaning: "airplane" },
  { level: "HSK1", word: "出租车", pinyin: "chūzūchē", meaning: "taxi" },
  { level: "HSK1", word: "电视", pinyin: "diànshì", meaning: "television" },
  { level: "HSK1", word: "电脑", pinyin: "diànnǎo", meaning: "computer" },
  { level: "HSK1", word: "电影", pinyin: "diànyǐng", meaning: "movie" },
  { level: "HSK1", word: "天气", pinyin: "tiānqì", meaning: "weather" },
  { level: "HSK1", word: "猫", pinyin: "māo", meaning: "cat" },
  { level: "HSK1", word: "狗", pinyin: "gǒu", meaning: "dog" },
  { level: "HSK1", word: "东西", pinyin: "dōngxi", meaning: "thing; stuff" },
  { level: "HSK1", word: "人", pinyin: "rén", meaning: "person; people" },
  { level: "HSK1", word: "名字", pinyin: "míngzi", meaning: "name" },
  { level: "HSK1", word: "书", pinyin: "shū", meaning: "book" },
  { level: "HSK1", word: "汉语", pinyin: "hànyǔ", meaning: "Mandarin Chinese" },
  { level: "HSK1", word: "字", pinyin: "zì", meaning: "character" },
  { level: "HSK1", word: "桌子", pinyin: "zhuōzi", meaning: "desk; table" },
  { level: "HSK1", word: "椅子", pinyin: "yǐzi", meaning: "chair" },

  // ================================
  // HSK 2 Vocabulary (150 words)
  // ================================
  { level: "HSK2", word: "您", pinyin: "nín", meaning: "you (polite)" },
  { level: "HSK2", word: "它", pinyin: "tā", meaning: "it" },
  { level: "HSK2", word: "大家", pinyin: "dàjiā", meaning: "everyone" },
  { level: "HSK2", word: "每", pinyin: "měi", meaning: "every" },
  { level: "HSK2", word: "为什么", pinyin: "wèishénme", meaning: "why" },
  { level: "HSK2", word: "零", pinyin: "líng", meaning: "zero" },
  { level: "HSK2", word: "两", pinyin: "liǎng", meaning: "two (for counting)" },
  { level: "HSK2", word: "百", pinyin: "bǎi", meaning: "hundred" },
  { level: "HSK2", word: "千", pinyin: "qiān", meaning: "thousand" },
  { level: "HSK2", word: "第一", pinyin: "dìyī", meaning: "first" },
  { level: "HSK2", word: "次", pinyin: "cì", meaning: "time; occurrence" },
  { level: "HSK2", word: "件", pinyin: "jiàn", meaning: "item; piece" },
  { level: "HSK2", word: "别", pinyin: "bié", meaning: "don't; other" },
  { level: "HSK2", word: "非常", pinyin: "fēicháng", meaning: "extremely" },
  { level: "HSK2", word: "也", pinyin: "yě", meaning: "also" },
  { level: "HSK2", word: "还", pinyin: "hái", meaning: "still; also" },
  { level: "HSK2", word: "最", pinyin: "zuì", meaning: "most" },
  { level: "HSK2", word: "真", pinyin: "zhēn", meaning: "really" },
  {
    level: "HSK2",
    word: "正在",
    pinyin: "zhèngzài",
    meaning: "in the process of",
  },
  { level: "HSK2", word: "已经", pinyin: "yǐjīng", meaning: "already" },
  { level: "HSK2", word: "一起", pinyin: "yìqǐ", meaning: "together" },
  { level: "HSK2", word: "再", pinyin: "zài", meaning: "again" },
  { level: "HSK2", word: "就", pinyin: "jiù", meaning: "just; exactly" },
  {
    level: "HSK2",
    word: "因为……所以……",
    pinyin: "yīnwèi…suǒyǐ…",
    meaning: "because… therefore…",
  },
  {
    level: "HSK2",
    word: "虽然……但是……",
    pinyin: "suīrán…dànshì…",
    meaning: "although… but…",
  },
  { level: "HSK2", word: "从", pinyin: "cóng", meaning: "from" },
  { level: "HSK2", word: "比", pinyin: "bǐ", meaning: "compare; than" },
  { level: "HSK2", word: "往", pinyin: "wǎng", meaning: "toward" },
  { level: "HSK2", word: "离", pinyin: "lí", meaning: "from; away from" },
  { level: "HSK2", word: "得", pinyin: "de", meaning: "(complement particle)" },
  { level: "HSK2", word: "着", pinyin: "zhe", meaning: "(aspect particle)" },
  {
    level: "HSK2",
    word: "过",
    pinyin: "guò",
    meaning: "(past experience marker)",
  },
  { level: "HSK2", word: "吧", pinyin: "ba", meaning: "(suggestion particle)" },
  { level: "HSK2", word: "机场", pinyin: "jīchǎng", meaning: "airport" },
  { level: "HSK2", word: "教室", pinyin: "jiàoshì", meaning: "classroom" },
  { level: "HSK2", word: "房间", pinyin: "fángjiān", meaning: "room" },
  { level: "HSK2", word: "路", pinyin: "lù", meaning: "road; street" },
  { level: "HSK2", word: "左边", pinyin: "zuǒbiān", meaning: "left side" },
  { level: "HSK2", word: "右边", pinyin: "yòubiān", meaning: "right side" },
  { level: "HSK2", word: "外", pinyin: "wài", meaning: "outside" },
  { level: "HSK2", word: "旁边", pinyin: "pángbiān", meaning: "beside" },
  {
    level: "HSK2",
    word: "一下",
    pinyin: "yīxià",
    meaning: "a bit; for a moment",
  },
  { level: "HSK2", word: "早上", pinyin: "zǎoshàng", meaning: "morning" },
  {
    level: "HSK2",
    word: "晚上",
    pinyin: "wǎnshàng",
    meaning: "evening; night",
  },
  { level: "HSK2", word: "小时", pinyin: "xiǎoshí", meaning: "hour" },
  { level: "HSK2", word: "时间", pinyin: "shíjiān", meaning: "time" },
  { level: "HSK2", word: "去年", pinyin: "qùnián", meaning: "last year" },
  { level: "HSK2", word: "丈夫", pinyin: "zhàngfu", meaning: "husband" },
  { level: "HSK2", word: "妻子", pinyin: "qīzi", meaning: "wife" },
  { level: "HSK2", word: "男人", pinyin: "nánrén", meaning: "man" },
  { level: "HSK2", word: "女人", pinyin: "nǚrén", meaning: "woman" },
  {
    level: "HSK2",
    word: "服务员",
    pinyin: "fúwùyuán",
    meaning: "waiter/waitress",
  },
  { level: "HSK2", word: "鱼", pinyin: "yú", meaning: "fish" },
  { level: "HSK2", word: "羊肉", pinyin: "yángròu", meaning: "mutton" },
  { level: "HSK2", word: "牛奶", pinyin: "niúnǎi", meaning: "milk" },
  { level: "HSK2", word: "鸡蛋", pinyin: "jīdàn", meaning: "egg" },
  { level: "HSK2", word: "西瓜", pinyin: "xīguā", meaning: "watermelon" },
  { level: "HSK2", word: "咖啡", pinyin: "kāfēi", meaning: "coffee" },
  { level: "HSK2", word: "药", pinyin: "yào", meaning: "medicine" },
  { level: "HSK2", word: "手机", pinyin: "shǒujī", meaning: "cellphone" },
  { level: "HSK2", word: "手表", pinyin: "shǒubiǎo", meaning: "watch" },
  { level: "HSK2", word: "眼睛", pinyin: "yǎnjīng", meaning: "eye" },
  { level: "HSK2", word: "身体", pinyin: "shēntǐ", meaning: "body" },
  { level: "HSK2", word: "公共汽车", pinyin: "gōnggòngqìchē", meaning: "bus" },
  { level: "HSK2", word: "报纸", pinyin: "bàozhǐ", meaning: "newspaper" },
  { level: "HSK2", word: "题", pinyin: "tí", meaning: "topic; question" },
  { level: "HSK2", word: "课", pinyin: "kè", meaning: "lesson; class" },
  { level: "HSK2", word: "姓", pinyin: "xìng", meaning: "surname" },
  {
    level: "HSK2",
    word: "问题",
    pinyin: "wèntí",
    meaning: "question; problem",
  },
  { level: "HSK2", word: "事情", pinyin: "shìqing", meaning: "matter; affair" },
  { level: "HSK2", word: "考试", pinyin: "kǎoshì", meaning: "exam; test" },
  { level: "HSK2", word: "票", pinyin: "piào", meaning: "ticket" },
  { level: "HSK2", word: "意思", pinyin: "yìsi", meaning: "meaning; idea" },
  { level: "HSK2", word: "颜色", pinyin: "yánsè", meaning: "color" },
  { level: "HSK2", word: "铅笔", pinyin: "qiānbǐ", meaning: "pencil" },
  { level: "HSK2", word: "面条", pinyin: "miàntiáo", meaning: "noodle" },
  {
    level: "HSK2",
    word: "老板",
    pinyin: "lǎobǎn",
    meaning: "boss; shop owner",
  },
  {
    level: "HSK2",
    word: "您们",
    pinyin: "nínmen",
    meaning: "you (polite, plural)",
  },
  { level: "HSK2", word: "道", pinyin: "dào", meaning: "way; path; to speak" },
  { level: "HSK2", word: "出", pinyin: "chū", meaning: "to go out" },
  {
    level: "HSK2",
    word: "决定",
    pinyin: "juédìng",
    meaning: "to decide; decision",
  },
  { level: "HSK2", word: "同意", pinyin: "tóngyì", meaning: "to agree" },
  { level: "HSK2", word: "答案", pinyin: "dá'àn", meaning: "answer" },
  { level: "HSK2", word: "解释", pinyin: "jiěshì", meaning: "to explain" },
  {
    level: "HSK2",
    word: "记",
    pinyin: "jì",
    meaning: "to record; to remember",
  },
  { level: "HSK2", word: "参加", pinyin: "cānjiā", meaning: "to participate" },
  { level: "HSK2", word: "组织", pinyin: "zǔzhī", meaning: "to organize" },
  { level: "HSK2", word: "了解", pinyin: "liǎojiě", meaning: "to understand" },
  { level: "HSK2", word: "练习", pinyin: "liànxí", meaning: "to practice" },
  { level: "HSK2", word: "复习", pinyin: "fùxí", meaning: "to review" },
  { level: "HSK2", word: "学期", pinyin: "xuéqī", meaning: "semester" },
  { level: "HSK2", word: "成绩", pinyin: "chéngjì", meaning: "grade; score" },
  {
    level: "HSK2",
    word: "课程",
    pinyin: "kèchéng",
    meaning: "course; curriculum",
  },
  {
    level: "HSK2",
    word: "专业",
    pinyin: "zhuānyè",
    meaning: "major; specialty",
  },
  { level: "HSK2", word: "学科", pinyin: "xuékē", meaning: "subject" },
  { level: "HSK2", word: "研究", pinyin: "yánjiū", meaning: "to research" },
  { level: "HSK2", word: "经验", pinyin: "jīngyàn", meaning: "experience" },
  { level: "HSK2", word: "知识", pinyin: "zhīshì", meaning: "knowledge" },
  { level: "HSK2", word: "软件", pinyin: "ruǎnjiàn", meaning: "software" },
  {
    level: "HSK2",
    word: "网络",
    pinyin: "wǎngluò",
    meaning: "network; internet",
  },
  { level: "HSK2", word: "信息", pinyin: "xìnxī", meaning: "information" },
  { level: "HSK2", word: "资料", pinyin: "zīliào", meaning: "materials; data" },
  { level: "HSK2", word: "问卷", pinyin: "wènjuàn", meaning: "questionnaire" },
  { level: "HSK2", word: "数据", pinyin: "shùjù", meaning: "data" },
  { level: "HSK2", word: "经济", pinyin: "jīngjì", meaning: "economy" },
  {
    level: "HSK2",
    word: "发展",
    pinyin: "fāzhǎn",
    meaning: "to develop; development",
  },
  { level: "HSK2", word: "世界", pinyin: "shìjiè", meaning: "world" },
  { level: "HSK2", word: "国家", pinyin: "guójiā", meaning: "country; nation" },
  { level: "HSK2", word: "政府", pinyin: "zhèngfǔ", meaning: "government" },
  { level: "HSK2", word: "社会", pinyin: "shèhuì", meaning: "society" },
  { level: "HSK2", word: "文化", pinyin: "wénhuà", meaning: "culture" },
  { level: "HSK2", word: "历史", pinyin: "lìshǐ", meaning: "history" },
  { level: "HSK2", word: "自然", pinyin: "zìrán", meaning: "nature" },
  { level: "HSK2", word: "环境", pinyin: "huánjìng", meaning: "environment" },
  { level: "HSK2", word: "法律", pinyin: "fǎlǜ", meaning: "law" },
  {
    level: "HSK2",
    word: "规则",
    pinyin: "guīzé",
    meaning: "rules; regulations",
  },
  { level: "HSK2", word: "传统", pinyin: "chuántǒng", meaning: "tradition" },
  { level: "HSK2", word: "现代", pinyin: "xiàndài", meaning: "modern" },
  { level: "HSK2", word: "简单", pinyin: "jiǎndān", meaning: "simple" },
  { level: "HSK2", word: "注意", pinyin: "zhùyì", meaning: "to pay attention" },
  { level: "HSK2", word: "帮忙", pinyin: "bāngmáng", meaning: "to help out" },
  { level: "HSK2", word: "回答", pinyin: "huídá", meaning: "to answer" },
  { level: "HSK2", word: "介绍", pinyin: "jièshào", meaning: "to introduce" },
  {
    level: "HSK2",
    word: "感谢",
    pinyin: "gǎnxiè",
    meaning: "to thank; grateful",
  },
  { level: "HSK2", word: "可能", pinyin: "kěnéng", meaning: "possibly; may" },
  { level: "HSK2", word: "改变", pinyin: "gǎibiàn", meaning: "to change" },
  {
    level: "HSK2",
    word: "关系",
    pinyin: "guānxi",
    meaning: "relationship; matter",
  },
  { level: "HSK2", word: "准备", pinyin: "zhǔnbèi", meaning: "to prepare" },
  { level: "HSK2", word: "解决", pinyin: "jiějué", meaning: "to solve" },
  { level: "HSK2", word: "使用", pinyin: "shǐyòng", meaning: "to use" },
  { level: "HSK2", word: "希望", pinyin: "xīwàng", meaning: "to hope" },
  { level: "HSK2", word: "适应", pinyin: "shìyìng", meaning: "to adapt" },
  { level: "HSK2", word: "选择", pinyin: "xuǎnzé", meaning: "to choose" },
  { level: "HSK2", word: "节目", pinyin: "jiémù", meaning: "program; show" },
  { level: "HSK2", word: "正确", pinyin: "zhèngquè", meaning: "correct" },
  { level: "HSK2", word: "意见", pinyin: "yìjiàn", meaning: "opinion" },
  { level: "HSK2", word: "建议", pinyin: "jiànyì", meaning: "suggestion" },
  { level: "HSK2", word: "讨论", pinyin: "tǎolùn", meaning: "to discuss" },
  { level: "HSK2", word: "内容", pinyin: "nèiróng", meaning: "content" },
  {
    level: "HSK2",
    word: "文章",
    pinyin: "wénzhāng",
    meaning: "article; essay",
  },
  { level: "HSK2", word: "句子", pinyin: "jùzi", meaning: "sentence" },
  { level: "HSK2", word: "字典", pinyin: "zìdiǎn", meaning: "dictionary" },
  {
    level: "HSK2",
    word: "翻译",
    pinyin: "fānyì",
    meaning: "to translate; translation",
  },
  { level: "HSK2", word: "读音", pinyin: "dúyīn", meaning: "pronunciation" },
  { level: "HSK2", word: "拼音", pinyin: "pīnyīn", meaning: "pinyin" },
  {
    level: "HSK2",
    word: "练习册",
    pinyin: "liànxícè",
    meaning: "exercise book",
  },
  { level: "HSK2", word: "课本", pinyin: "kèběn", meaning: "textbook" },
  {
    level: "HSK2",
    word: "学习资料",
    pinyin: "xuéxí zīliào",
    meaning: "study materials",
  },
  { level: "HSK2", word: "理解", pinyin: "lǐjiě", meaning: "to understand" },
  {
    level: "HSK2",
    word: "记忆",
    pinyin: "jìyì",
    meaning: "memory; to remember",
  },
];
